# -*- mode: python ; coding: utf-8 -*-
# Build with:  pyinstaller --noconfirm mod_updater.spec
# Output: dist/mod_updater/ (Windows, Linux) and dist/Minecraft Mod Updater.app (macOS)
import os
import re
import sys

from PyInstaller.utils.hooks import collect_data_files

# app_version.py is generated by the release workflow
APP_VERSION = '0.0.0'
if os.path.exists('app_version.py'):
    APP_VERSION = re.search(r'"(.+)"', open('app_version.py', encoding='utf-8-sig').read()).group(1)

if sys.platform == 'win32':
    icon = ['updater-logo.ico']
elif sys.platform == 'darwin':
    icon = ['updater-logo.png']  # converted to .icns by PyInstaller (needs Pillow)
else:
    icon = None

a = Analysis(
    ['mod_updater.py'],
    pathex=[],
    binaries=[],
    datas=collect_data_files('customtkinter') + [
        ('updater-logo.ico', '.'),
        ('updater-logo.png', '.'),
    ],
    # PIL._tkinter_finder is needed by ImageTk on Linux and not detected automatically
    hiddenimports=['truststore', 'PIL.ImageTk', 'PIL._tkinter_finder'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='mod_updater',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=icon,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='mod_updater',
)

if sys.platform == 'darwin':
    app = BUNDLE(
        coll,
        name='Minecraft Mod Updater.app',
        icon=icon[0],
        bundle_identifier='com.codeinia.minecraftmodupdater',
        version=APP_VERSION,
        info_plist={
            'CFBundleDisplayName': 'Minecraft Mod Updater',
            'NSHighResolutionCapable': True,
        },
    )
